import type { Template } from "../types/element";

export const configTemplates: Template[] = [
  {
    id: "landing-page",
    name: "Landing Page",
    description:
      "A hero section with a large heading, paragraph, and image in a centered single-column layout.",
    layout: "single-column",
    pageSettings: {
      backgroundColor: "#ffffff",
      contentWidth: 900,
    },
    elements: [
      {
        id: "heading-1",
        type: "heading",
        text: "Welcome to Our Product",
        fontSize: 48,
        fontWeight: "bold",
        fontStyle: "normal",
        color: "#1a1a2e",
        alignment: "center",
      },
      {
        id: "paragraph-1",
        type: "paragraph",
        text: "Give your business a boost with a beautifully crafted homepage.",
        fontSize: 18,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#444444",
        alignment: "center",
      },
      {
        id: "section-1",
        type: "section",
        reversed: false,
        gap: 32,
        backgroundColor: "#f8f9fa",
        sectionPadding: 32,
        borderRadius: 12,
        children: [
          {
            id: "section-1-img",
            type: "image",
            src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80",
            alt: "Feature image",
            width: 100,
            alignment: "center",
          },
          {
            id: "section-1-text-group",
            type: "heading",
            text: "One column Layout",
            fontSize: 28,
            fontWeight: "bold",
            fontStyle: "italic",
            color: "#1a1a2e",
            alignment: "left",
          },
        ],
      },
      {
        id: "section-2",
        type: "section",
        reversed: true,
        gap: 32,
        backgroundColor: "#ffffff",
        sectionPadding: 32,
        borderRadius: 12,
        children: [
          {
            id: "section-2-img",
            type: "image",
            src: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=600&q=80",
            alt: "Design image",
            width: 100,
            alignment: "center",
          },
          {
            id: "section-2-text",
            type: "paragraph",
            text: "Our platform provides everything you need to create stunning websites with zero coding required.",
            fontSize: 16,
            fontWeight: "normal",
            fontStyle: "normal",
            color: "#555555",
            alignment: "left",
          },
        ],
      },
    ],
  },
  {
    id: "portfolio-card",
    name: "Portfolio Card",
    description: "A two-column card layout with an image on one side and text on the other.",
    layout: "two-column",
    pageSettings: {
      backgroundColor: "#f0f4f8",
      contentWidth: 1000,
    },
    elements: [
      {
        id: "image-1",
        type: "image",
        src: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=600&q=80",
        alt: "Portfolio image",
        width: 100,
        alignment: "center",
      },
      {
        id: "heading-1",
        type: "heading",
        text: "Two Column Layout",
        fontSize: 36,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#2d3436",
        alignment: "left",
      },
      {
        id: "paragraph-1",
        type: "paragraph",
        text: "Today is the day to build the business of your dreams. Share your mission with the world — and blow your customers away.",
        fontSize: 16,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#636e72",
        alignment: "left",
      },
    ],
  },
];
